name: Bug Bounty Recon

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */10 * * *"

env:
  TARGET: duolingo.com

jobs:
  run-recon:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        ref: main
        token: ${{ secrets.PAT }}

    - name: Install Tools
      run: |
        echo "Installing Aquatone"
        sudo apt-get install -y ruby ruby-dev
        sudo gem install aquatone

        echo "Installing assetfinder"
        sudo apt-get install -y golang-go
        wget https://github.com/tomnomnom/assetfinder/releases/download/v0.1.1/assetfinder-linux-amd64-0.1.1.tgz
        tar -xvf assetfinder-linux-amd64-0.1.1.tgz
        chmod +x *

    - name: Run Recon
      run: |
        echo "Running recon on $TARGET"
        echo "Running subdomain enumeration using assetfinder"
        ./assetfinder $TARGET >> subdomains.txt
         echo "Running screenshot using Aquatone"
        aquatone-discover --wordlist subdomains.txt
        aquatone-scan --ports xlarge subdomains.txt

    - name: Upload Screenshots
      uses: actions/upload-artifact@v2
      with:
        name: screenshots
        path: aquatone

    - name: send default message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: "Bug bounty recon on $TARGET has completed. Screenshots are available in the GitHub Actions workflow."
