name: Bug Bounty Recon

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */10 * * *"

env:
  TARGET: duolingo.com

jobs:
  run-recon:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        ref: main
        token: ${{ secrets.PAT }}

    - name: Install Tools
      run: |
        echo "Installing EyeWitness"
        sudo apt-get install -y python3 python3-pip
        sudo pip3 install selenium
        wget https://github.com/FortyNorthSecurity/EyeWitness/archive/refs/tags/v20221203.1.tar.gz
        tar -xf v20221203.1.tar.gz
        rm v20221203.1.tar.gz
        mv EyeWitness-20221203.1 EyeWitness

         echo "Installing assetfinder"
        sudo apt-get install -y golang-go
        wget https://github.com/tomnomnom/assetfinder/releases/download/v0.1.1/assetfinder-linux-amd64-0.1.1.tgz
        tar -xvf assetfinder-linux-amd64-0.1.1.tgz
        chmod +x *

    - name: Run Recon
      run: |
        echo "Running recon on $TARGET"
        echo "Running subdomain enumeration using assetfinder"
        ./assetfinder $TARGET >> subdomains.txt
        echo "Running screenshot using EyeWitness"
        python3 ./EyeWitness/EyeWitness.py -f subdomains.txt --headless


    - name: Upload Screenshots
      uses: actions/upload-artifact@v2
      with:
        name: screenshots
        path: EyeWitness/Reports

    - name: send default message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: "Bug bounty recon on $TARGET has completed. Screenshots are available in the GitHub Actions workflow."
