name: Bug Bounty Recon

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */10 * * *"

env:
  TARGET: duolingo.com

jobs:
  run-recon:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        ref: main
        token: ${{ secrets.PAT }}

    - name: Install Tools
      run: |
        echo "Installing EyeWitness"
        sudo apt-get install -y python3 python3-pip
        sudo pip3 install selenium
        git clone https://github.com/ChrisTruncer/EyeWitness.git

         echo "Installing assetfinder"
        sudo apt-get install -y golang-go
        wget https://objects.githubusercontent.com/github-production-release-asset-2e65be/193392376/71a80e80-5fc4-11eb-9534-51965f0b3d4c?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20230205%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230205T190917Z&X-Amz-Expires=300&X-Amz-Signature=1891905ea95146078d64979e048a7fcab362077444f5fdbe52cdc7600dcacb59&X-Amz-SignedHeaders=host&actor_id=61207401&key_id=0&repo_id=193392376&response-content-disposition=attachment%3B%20filename%3Dassetfinder-linux-amd64-0.1.1.tgz&response-content-type=application%2Foctet-stream
        tar -xvf assetfinder-linux-amd64-0.1.1.tgz
        chmod +x *

    - name: Run Recon
      run: |
        echo "Running recon on $TARGET"
        echo "Running subdomain enumeration using assetfinder"
        ./assetfinder-linux-amd64-0.1.1/assetfinder $TARGET >> subdomains.txt
        echo "Running screenshot using EyeWitness"
        EyeWitness/EyeWitness.py -f subdomains.txt --headless


    - name: Upload Screenshots
      uses: actions/upload-artifact@v2
      with:
        name: screenshots
        path: EyeWitness/Reports

    - name: Send Telegram Notification
      if: always()
      uses: appleboy/telegram-action@master
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      with:
        message: "Bug bounty recon on $TARGET has completed. Screenshots are available in the GitHub Actions workflow."
